{{- if and .Values.global.middleware .Values.middleware -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  labels: {{ include "hedera-mirror-web3.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-web3.fullname" . }}
  namespace: {{ include "hedera-mirror-web3.namespace" . }}
spec:
  chain:
    middlewares:
{{- range .Values.middleware }}
      - name: {{ include "hedera-mirror-web3.fullname" $ }}-{{ keys . | first | kebabcase }}
{{- end }}

{{- range .Values.middleware }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  labels: {{ include "hedera-mirror-web3.labels" $ | nindent 4 }}
  name: {{ include "hedera-mirror-web3.fullname" $ }}-{{ keys . | first | kebabcase }}
  namespace: {{ include "hedera-mirror-web3.namespace" $ }}
spec:
  {{- . | toYaml | nindent 2 }}
{{- end }}
{{- end }}
