apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
  labels: {{ include "hedera-mirror-grpc.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-grpc.fullname" . }}
  namespace: {{ include "hedera-mirror-grpc.namespace" . }}
spec:
  {{- if .Values.replicas }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels: {{ include "hedera-mirror-grpc.selectorLabels" . | nindent 6 }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels: {{ include "hedera-mirror-grpc.selectorLabels" . | nindent 8 }}
    spec:
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/usr/etc/hedera-mirror-grpc/"
            {{- with .Values.extraEnv }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          envFrom: {{ tpl (toYaml .Values.envFrom) . | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          ports:
            - containerPort: 5600
              name: grpc
              protocol: TCP
            - containerPort: 8081
              name: http
              protocol: TCP
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/etc/hedera-mirror-grpc
            - name: tmp
              mountPath: /tmp # Vertx needs a writable cache directory
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "hedera-mirror-grpc.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      volumes:
        - name: config
          secret:
            defaultMode: 420
            secretName: {{ include "hedera-mirror-grpc.fullname" . }}
        - name: tmp
          emptyDir: {}
        {{- with .Values.extraVolumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
