apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
  labels: {{ include "hedera-mirror-grpc.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-grpc.fullname" . }}
  namespace: {{ include "hedera-mirror-grpc.namespace" . }}
spec:
  {{- if .Values.replicas }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels: {{ include "hedera-mirror-grpc.selectorLabels" . | nindent 6 }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels: {{ include "hedera-mirror-grpc.selectorLabels" . | nindent 8 }}
    spec:
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
            {{- if kindIs "string" $value }}
              value: {{ tpl $value $ | quote }}
            {{- else }}
            {{- tpl (toYaml $value) $ | nindent 14 }}
            {{- end }}
            {{- end }}
          envFrom: {{ tpl (toYaml .Values.envFrom) . | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          ports:
            - containerPort: 5600
              name: grpc
              protocol: TCP
            - containerPort: 8081
              name: http
              protocol: TCP
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- range $name, $config := .Values.volumeMounts }}
            - name: {{ $name }}
            {{- tpl (toYaml $config) $ | nindent 14 }}
            {{- end }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "hedera-mirror-grpc.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      volumes:
        {{- range $name, $config := .Values.volumes }}
        - name: {{ $name }}
        {{- tpl (toYaml $config) $ | nindent 10 }}
        {{- end }}
