apiVersion: v1
kind: Service
metadata:
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
  labels: {{- include "hedera-mirror-grpc.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-grpc.fullname" . }}
  namespace: {{ include "hedera-mirror-grpc.namespace" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "hedera-mirror-grpc.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
