{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "hedera-mirror-grpc.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-grpc.serviceAccountName" . }}
  namespace: {{ include "hedera-mirror-grpc.namespace" . }}
{{- end -}}
