# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/hedera-mirror-rest"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/hedera-mirror-rest/monitoring/monitor_apis"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/hedera-mirror-rest/check-state-proof"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/hedera-mirror-rosetta"
    schedule:
      interval: "weekly"
