# This file contains application defaults and shouldn't be modified. See docs/configuration.md for how to override.
hedera:
  mirror:
    rosetta:
      apiVersion: 1.4.10
      db:
        host: 127.0.0.1
        name: mirror_node
        password: mirror_rosetta_pass
        pool:
          maxIdleConnections: 20
          maxLifetime: 30
          maxOpenConnections: 100
        port: 5432
        username: mirror_rosetta
      log:
        level: info
      network: DEMO
      nodes: {}
      nodeVersion: 0
      online: true
      port: 5700
      realm: 0
      shard: 0
      version: 0.36.0-rc1
