hedera:
  mirror:
    rosetta:
      cache:
        entity:
          maxSize: 524288
      db:
        host: 127.0.0.1
        name: mirror_node
        password: mirror_rosetta_pass
        pool:
          maxIdleConnections: 20
          maxLifetime: 30
          maxOpenConnections: 100
        port: 5432
        statementTimeout: 20
        username: mirror_rosetta
      feature:
        subNetworkIdentifier: false
      http:
        idleTimeout: 10000000000
        readHeaderTimeout: 3000000000
        readTimeout: 5000000000
        writeTimeout: 10000000000
      log:
        level: info
      network: demo
      networkAddressBookUpdateFrequency: 24h
      nodes:
      nodeVersion: 0
      online: true
      port: 5700
      realm: 0
      response:
        maxTransactionsInBlock: 6000
      shard: 0
      shutdownTimeout: 10s
