{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels: {{- include "hedera-mirror-rest.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-rest.fullname" . }}
  namespace: {{ include "hedera-mirror-rest.namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hedera-mirror-rest.fullname" . }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.utilization }}
{{- end -}}
