apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "hedera-mirror-rest.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-rest.fullname" . }}
  namespace: {{ include "hedera-mirror-rest.namespace" . }}
type: Opaque
stringData:
  application.yaml: |-
    # Until Helm supports exporting values from parent to subcharts (https://github.com/helm/helm/pull/7477),
    # we must manually merge the DB credentials from REST chart into Importer chart to stay DRY.
    {{- if and .Values.global.rest (hasKey .Values.config.hedera.mirror.rest "db") -}}
    {{- $_ := set .Values.config.hedera.mirror.rest.db "password" .Values.global.rest.password -}}
    {{- $_ := set .Values.config.hedera.mirror.rest.db "username" .Values.global.rest.username -}}
    {{- end -}}
    {{- toYaml .Values.config | nindent 4 }}
