properties:
  importer.config.hedera.mirror.importer.downloader.accessKey:
    default: ""
    type: string
  importer.config.hedera.mirror.importer.downloader.cloudProvider:
    type: string
    default: S3
  importer.config.hedera.mirror.importer.downloader.secretKey:
    default: ""
    type: string
  importer.config.hedera.mirror.importer.network:
    default: "DEMO"
    type: string
