applicationResource:
  enabled: true
  partnerId: mirror-node-public
  partnerName: mirror-node-public
  solutionId: hedera-mirror-node
  version: ''

global:
  db:
    host: RELEASE-NAME-postgres-postgresql
  useReleaseForNameLabel: true

grpc:
  config:
    hedera:
      mirror:
        grpc:
          listener:
            type: NOTIFY
    management:
      endpoint:
        health:
          group:
            readiness:
              exclude: redis
  hpa:
    enabled: false
  ingress:
    enabled: false
  rbac:
    enabled: false
  service:
    type: LoadBalancer
  serviceAccount:
    create: false

importer:
  config:
    hedera:
      mirror:
        importer:
          downloader:
            cloudProvider: GCP
          parser:
            record:
              entity:
                notify:
                  enabled: true
                redis:
                  enabled: false
    management:
      endpoint:
        health:
          group:
            readiness:
              exclude: redis
  rbac:
    enabled: false
  replicas: 1
  serviceAccount:
    create: false

monitor:
  enabled: false

postgresql:
  enabled: true
  pgpool:
    replicaCount: 0
  postgresql:
    upgradeRepmgrExtension: true  # Upgrade repmgr version to 5.2 or else container spinup fails
  postgresqlImage:
    tag: 12.5.0-debian-10-r88

redis:
  enabled: false

rest:
  config:
    hedera:
      mirror:
        rest:
          metrics:
            config:
              enabled: false
  hpa:
    enabled: false
  ingress:
    enabled: false
  rbac:
    enabled: false
  serviceAccount:
    create: false
  service:
    type: LoadBalancer

rosetta:
  enabled: false

timescaledb:
  enabled: false

web3:
  enabled: false