{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: {{- include "hedera-mirror-monitor.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-monitor.fullname" . }}
  namespace: {{ include "hedera-mirror-monitor.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hedera-mirror-monitor.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "hedera-mirror-monitor.serviceAccountName" . }}
{{- end -}}
