{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "hedera-mirror-monitor.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-monitor.serviceAccountName" . }}
  namespace: {{ include "hedera-mirror-monitor.namespace" . }}
{{- end -}}
