{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels: {{ include "hedera-mirror-rosetta.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-rosetta.fullname" . }}
  namespace: {{ include "hedera-mirror-rosetta.namespace" . }}
spec:
  behavior: {{ toYaml .Values.hpa.behavior | nindent 4 }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics: {{ tpl (toYaml .Values.hpa.metrics) . | nindent 4 }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hedera-mirror-rosetta.fullname" . }}
{{- end -}}
