{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels: {{ include "hedera-mirror-rosetta.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-rosetta.fullname" . }}
  namespace: {{ include "hedera-mirror-rosetta.namespace" . }}
spec:
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  selector:
    matchLabels: {{ include "hedera-mirror-rosetta.selectorLabels" . | nindent 6 }}
{{- end -}}
