citus:
  enabled: true
graphql:
  test:
    defaultAccount: 111571
importer:
  env:
    SPRING_FLYWAY_PLACEHOLDERS_SHARDCOUNT: "2"
    SPRING_FLYWAY_PLACEHOLDERS_PARTITIONSTARTDATE: "'0 days'"
    SPRING_PROFILES_ACTIVE: v2
monitor:
  enabled: false
postgresql:
  enabled: false
rest:
  monitor:
    config: |-
      {
        "freshness": false,
        "network": { "enabled": false },
        "servers": [
          {
            "baseUrl": "http://{{ .Release.Name }}-rest:{{ .Values.service.port }}",
            "name": "kubernetes"
          }
        ],
        "stateproof": { "enabled": false }
      }
rosetta:
  test:
    enabled: false
