graphql:
  enabled: true
  test:
    defaultAccount: 111146
importer:
  env:
    SPRING_FLYWAY_PLACEHOLDERS_HASHSHARDCOUNT: "2"
    SPRING_FLYWAY_PLACEHOLDERS_IDPARTITIONSIZE: "1000000000000000"
    SPRING_FLYWAY_PLACEHOLDERS_PARTITIONTIMEINTERVAL: "'10 years'"
    SPRING_FLYWAY_PLACEHOLDERS_SHARDCOUNT: "2"
    SPRING_PROFILES_ACTIVE: v2
  # Ensure importer has time to start stream processing after startup
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 15
    successThreshold: 2
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
monitor:
  enabled: false
postgresql:
  enabled: false
rest:
  monitor:
    config: |-
      {
        "freshness": false,
        "network": { "enabled": false },
        "servers": [
          {
            "baseUrl": "http://{{ .Release.Name }}-rest:{{ .Values.service.port }}",
            "name": "kubernetes"
          }
        ],
        "stateproof": { "enabled": false }
      }
  resources:
    requests:
      cpu: 200m
restjava:
  enabled: true
  resources:
    requests:
      cpu: 200m
rosetta:
  enabled: true
  test:
    enabled: false
stackgres:
  enabled: true
  podAntiAffinity: false
web3:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

