graphql:
  test:
    defaultAccount: 111146
importer:
  env:
    SPRING_FLYWAY_PLACEHOLDERS_PARTITIONSTARTDATE: "(CURRENT_TIMESTAMP - '1970-01-01 00:00:00.000')"
    SPRING_FLYWAY_PLACEHOLDERS_PARTITIONTIMEINTERVAL: "'10 years'"
    SPRING_FLYWAY_PLACEHOLDERS_SHARDCOUNT: "2"
    SPRING_PROFILES_ACTIVE: v2
  # Ensure importer has time to start stream processing after startup
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 15
    successThreshold: 2
monitor:
  enabled: false
postgresql:
  enabled: false
rest:
  monitor:
    config: |-
      {
        "freshness": false,
        "network": { "enabled": false },
        "servers": [
          {
            "baseUrl": "http://{{ .Release.Name }}-rest:{{ .Values.service.port }}",
            "name": "kubernetes"
          }
        ],
        "stateproof": { "enabled": false }
      }
  resources:
    requests:
      cpu: 200m
rosetta:
  test:
    enabled: false
stackgres:
  enabled: true
  podAntiAffinity: false
