{{- if .Values.zfs.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.zfs.init.serviceAccount.iAmName }}
  labels: {{ include "hedera-mirror-common.labels" . | nindent 4 }}
  name: {{ .Values.zfs.init.serviceAccount.name }}
  namespace: {{ include "hedera-mirror-common.namespace" . }}
{{- end -}}