apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mirror
resources:
- ../../base/common
- ../../base/testkube
- helmrelease.yaml
- sealed-secret.yaml
- sealed-secret-grafana-cloud.yaml

