{{- if .Values.rbac.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels: {{ include "hedera-mirror-graphql.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-graphql.fullname" . }}
  namespace: {{ include "hedera-mirror-graphql.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
{{- end -}}
