dependencies:
  - alias: grpc
    condition: grpc.enabled
    name: hedera-mirror-grpc
    repository: file://../hedera-mirror-grpc
    version: ^0.1.0
  - alias: importer
    condition: importer.enabled
    name: hedera-mirror-importer
    repository: file://../hedera-mirror-importer
    version: ^0.1.0
  - alias: loki-stack
    condition: loki-stack.enabled
    name: loki-stack
    version: 0.34.2
    repository: https://grafana.github.io/loki/charts
  - alias: postgresql
    condition: postgresql.enabled
    name: postgresql-ha
    repository: https://charts.bitnami.com/bitnami
    version: ~2.3.0
  - alias: prometheus-adapter
    condition: prometheus-adapter.enabled
    name: prometheus-adapter
    version: ~2.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - alias: prometheus-operator
    condition: prometheus-operator.enabled
    name: prometheus-operator
    repository: https://kubernetes-charts.storage.googleapis.com
    version: ~8.12.12
  - alias: rest
    condition: rest.enabled
    name: hedera-mirror-rest
    repository: file://../hedera-mirror-rest
    version: ^0.1.0
