dependencies:
  - alias: grpc
    condition: grpc.enabled
    name: hedera-mirror-grpc
    repository: file://../hedera-mirror-grpc
    version: ^0.4.0
  - alias: importer
    condition: importer.enabled
    name: hedera-mirror-importer
    repository: file://../hedera-mirror-importer
    version: ^0.4.0
  - alias: postgresql
    condition: postgresql.enabled
    name: postgresql-ha
    repository: https://charts.bitnami.com/bitnami
    version: ~3.4.3
  - alias: rest
    condition: rest.enabled
    name: hedera-mirror-rest
    repository: file://../hedera-mirror-rest
    version: ^0.4.0
