{{- if .Values.applicationResource.enabled -}}
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  annotations:
    kubernetes-engine.cloud.google.com/icon: data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{ "partner_id": "{{.Values.applicationResource.partnerId}}", "partner_name": "{{.Values.applicationResource.partnerName}}", "product_id": "{{.Values.applicationResource.solutionId}}" }'
  labels: {{ include "hedera-mirror.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ include "hedera-mirror.namespace" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hedera-mirror.name" . }}
  addOwnerRef: true
  componentKinds:
    - group: v1
      kind: ConfigMap
    - group: apps/v1
      kind: Deployment
    - group: v1
      kind: Pod
    - group: policy/v1
      kind: PodDisruptionBudget
    - group: v1
      kind: Secret
    - group: v1
      kind: Service
    - group: apps/v1
      kind: StatefulSet
  descriptor:
    description: Hedera Mirror Node mirrors transaction data from Hedera nodes and serves it via GRPC and REST APIs
    icons:
      - src: https://camo.githubusercontent.com/cca6b767847bb8ca5c7059481ba13a5fc81c5938/68747470733a2f2f7777772e6865646572612e636f6d2f6c6f676f2d6361706974616c2d686261722d776f72646d61726b2e6a7067
        type: image/jpeg
        size: 786x162
    keywords:
      - blockchain
      - dlt
      - hedera
      - hashgraph
      - mirror
    links:
      - description: Discord
        url: https://hedera.com/discord
      - description: Documentation
        url: https://docs.hedera.com
      - description: Source Repository
        url: https://github.com/hashgraph/hedera-mirror-node
      - description: User Guide
        url: https://github.com/hashgraph/hedera-mirror-node/blob/main/charts/marketplace/gcp/README.md
      - description: Website
        url: https://hedera.com
    maintainers:
      - name: Hedera Mirror Node team
        email: mirrornode@hedera.com
    notes: |
      To access the GRPC API:

        GRPC_IP=$(kubectl get service/{{ .Release.Name }}-grpc -n {{ include "hedera-mirror.namespace" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

        grpcurl -plaintext "${GRPC_IP}:5600" list

      To access the REST API:

        REST_IP=$(kubectl get service/{{ .Release.Name }}-rest -n {{ include "hedera-mirror.namespace" . }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

        curl -s "http://${REST_IP}/api/v1/transactions?limit=1"
    type: hedera-mirror-node
    version: {{ default .Chart.AppVersion .Values.applicationResource.version | quote }}
  {{- end }}
