{{- $name := "mirror-redis" -}}  # redis chart doesn't support template names
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "hedera-mirror.labels" . | nindent 4 }}
  name: {{ $name }}
  namespace: {{ include "hedera-mirror.namespace" . }}
stringData:
  {{- $secret := lookup "v1" "Secret" .Release.Namespace $name | default (dict) -}}
  {{- $passwords := $secret.data | default (dict) -}}
  {{- $redisHost := tpl .Values.redis.host . -}}
  {{- $redisPassword := coalesce .Values.redis.auth.password ($passwords.SPRING_REDIS_PASSWORD | default "" | b64dec) (randAlphaNum 40) }}

  SPRING_REDIS_HOST: "{{ $redisHost }}"
  SPRING_REDIS_PASSWORD: "{{ $redisPassword }}"

  {{- if and .Values.redis.enabled .Values.redis.sentinel.enabled }}
  SPRING_REDIS_SENTINEL_MASTER: "{{ .Values.redis.sentinel.masterSet }}"
  SPRING_REDIS_SENTINEL_NODES: "{{ print $redisHost ":" .Values.redis.sentinel.service.sentinelPort }}"
  SPRING_REDIS_SENTINEL_PASSWORD: "{{ $redisPassword }}"
  {{- end -}}
