{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "hedera-mirror.labels" . | nindent 4 }}
  name: {{ printf "%s-postgresql-init" .Release.Name  }}
  namespace: {{ include "hedera-mirror.namespace" . }}
type: Opaque
stringData:
  init_v1.sql: |-
    {{- $dbname := .Values.importer.config.hedera.mirror.importer.db.name }}
    {{- $password := .Values.importer.config.hedera.mirror.importer.db.password }}
    {{- $username := .Values.importer.config.hedera.mirror.importer.db.username }}
    {{- $grpcPassword := .Values.grpc.config.hedera.mirror.grpc.db.password }}
    {{- $grpcUsername := .Values.grpc.config.hedera.mirror.grpc.db.username }}
    create user {{ $username }} with createrole password '{{ $password }}';
    create database {{ $dbname }} with owner {{ $username }};
    \c {{ $dbname }};
    alter schema public owner to {{ $username }};
    create role viewer;
    grant connect on database {{ $dbname }} to viewer;
    grant select on all tables in schema public to viewer;
    alter default privileges for role {{ $username }} in schema public grant select on tables to viewer;
    create user {{ $grpcUsername }} password '{{ $grpcPassword }}' in role viewer;
    create extension pg_stat_statements;
{{- end -}}
