{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "hedera-mirror.labels" . | nindent 4 }}
  name: {{ printf "%s-pgpool-init" .Release.Name }}
  namespace: {{ include "hedera-mirror.namespace" . }}
type: Opaque
stringData:
  usernames: "{{ .Values.grpc.config.hedera.mirror.grpc.db.username }},{{ .Values.importer.config.hedera.mirror.importer.db.username }},{{ .Values.global.rest.username }}"
  passwords: "{{ .Values.grpc.config.hedera.mirror.grpc.db.password }},{{ .Values.importer.config.hedera.mirror.importer.db.password }},{{ .Values.global.rest.password }}"
{{- end -}}
