# See testing.md for documentation.
hedera:
  mirror:
    rest:
      db:
        host: 127.0.0.1
        name: mirror_node
        password: mirror_api_pass
        port: 5111
        username: mirror_api
      apiServer: 127.0.0.1:5551
      querySetsFile: /tmp/apiperftest/querySets.yml
      resultsDir: /tmp/apiperftest/
