# See testing.md for documentation.
hedera:
  mirror:
    db:
      host: 127.0.0.1
      port: 5432
      name: mirror_node
      apiPassword: mirror_api_pass
      apiUsername: mirror_api
    apiServer: 127.0.0.1:5551
    querySetsFile: /tmp/apiperftest/querySets.yml
    resultsFile: /tmp/apiperftest/apiResults.yml
