apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "gce"
  name: mirror
  namespace: mainnet
spec:
  ingressClassName: gce
  rules:
    - http:
        paths:
          - path: /actuator/health/cluster
            pathType: Exact
            backend:
              service:
                name: mirror-monitor
                port:
                  number: 80
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: mirror-rest
                port:
                  number: 80
          - path: /com.hedera.mirror.api.proto.ConsensusService
            pathType: Exact
            backend:
              service:
                name: mirror-grpc
                port:
                  number: 5600
          - path: /com.hedera.mirror.api.proto.NetworkService
            pathType: Exact
            backend:
              service:
                name: mirror-grpc
                port:
                  number: 5600
          - path: /grpc.reflection.v1alpha.ServerReflection
            pathType: Exact
            backend:
              service:
                name: mirror-grpc
                port:
                  number: 5600
          - path: /rosetta
            pathType: Prefix
            backend:
              service:
                name: mirror-rosetta
                port:
                  number: 80
          - path: /web3
            pathType: Prefix
            backend:
              service:
                name: mirror-web3
                port:
                  number: 80
