apiVersion: v2
appVersion: 0.87.0-SNAPSHOT
description: Hedera Mirror Importer downloads and validates file streams from the cloud and imports them into the database
home: https://github.com/hashgraph/hedera-mirror-node
icon: https://camo.githubusercontent.com/cca6b767847bb8ca5c7059481ba13a5fc81c5938/68747470733a2f2f7777772e6865646572612e636f6d2f6c6f676f2d6361706974616c2d686261722d776f72646d61726b2e6a7067
maintainers:
  - name: Hedera Mirror Node Team
    email: mirrornode@hedera.com
name: hedera-mirror-importer
sources:
  - https://github.com/hashgraph/hedera-mirror-node
version: 0.87.0-SNAPSHOT
