apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {{ toYaml .Values.annotations | nindent 4 }}
  labels: {{ include "hedera-mirror-importer.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-importer.fullname" . }}
  namespace: {{ include "hedera-mirror-importer.namespace" . }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels: {{ include "hedera-mirror-importer.selectorLabels" . | nindent 6 }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels: {{ include "hedera-mirror-importer.selectorLabels" . | nindent 8 }}
    spec:
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/usr/etc/hedera-mirror-importer/"
            {{- with .Values.extraEnv }}
            {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          envFrom: {{ tpl (toYaml .Values.envFrom) . | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe: {{ toYaml .Values.livenessProbe | nindent 12 }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe: {{ toYaml .Values.readinessProbe | nindent 12 }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /usr/etc/hedera-mirror-importer
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "hedera-mirror-importer.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      volumes:
        - name: config
          secret:
            defaultMode: 420
            secretName: {{ include "hedera-mirror-importer.fullname" . }}
        {{- with .Values.extraVolumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
