{{- if .Values.podDisruptionBudget.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels: {{- include "hedera-mirror-importer.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-importer.fullname" . }}
  namespace: {{ include "hedera-mirror-importer.namespace" . }}
spec:
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . | int }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . | int }}
  {{- end }}
  selector:
    matchLabels: {{- include "hedera-mirror-importer.selectorLabels" . | nindent 6 }}
{{- end -}}
