{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels: {{- include "hedera-mirror-importer.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-importer.fullname" . }}
  namespace: {{ include "hedera-mirror-importer.namespace" . }}
spec:
  podMetricsEndpoints:
  - interval: {{ .Values.podMonitor.interval }}
    path: /actuator/prometheus
    port: http
  selector:
    matchLabels: {{- include "hedera-mirror-importer.selectorLabels" . | nindent 6 }}
{{- end -}}
