{{- if .Values.rbac.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels: {{- include "hedera-mirror-importer.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-importer.fullname" . }}
  namespace: {{ include "hedera-mirror-importer.namespace" . }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "update", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch"]
{{- end -}}
