apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "hedera-mirror-importer.labels" . | nindent 4 }}
  name: {{ include "hedera-mirror-importer.fullname" . }}
  namespace: {{ include "hedera-mirror-importer.namespace" . }}
type: Opaque
stringData:
  application.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
