hedera:
  mirror:
    db:
      apiPassword: mirror_api_pass
      apiUsername: mirror_api
      host: 127.0.0.1
      name: mirror_node
      password: mirror_node_pass
      port: 5432
      username: mirror_node
    parser:
      record:
        pubsub:
          enabled: false
logging:
  level:
    root: warn
    com.hedera.mirror.importer: info
    org.flywaydb.core.internal.command.DbMigrate: info
    #org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  health:
    pubsub:
      # Just importing pubsub deps enables its health checker and it requires auth credentials.
      # Setting spring.cloud.gcp.pubsub.enabled=false is not enough to disable the pubsub health check.
      enabled: ${hedera.mirror.parser.record.pubsub.enabled}
  metrics:
    export:
      elastic:
        enabled: false
        index: mirror
        step: 30s
      prometheus:
        step: 30s
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: hedera-mirror-importer
  cloud:
    gcp:
      core: # Initializes credentials, which may be not set if pubsub is disabled.
        enabled: ${hedera.mirror.parser.record.pubsub.enabled}
      pubsub:
        enabled: ${hedera.mirror.parser.record.pubsub.enabled}
      credentials:
        location: ${hedera.mirror.parser.record.pubsub.credentialsLocation}
    kubernetes:
      reload:
        enabled: true
      secrets:
        paths: /usr/etc/${spring.application.name}
  datasource:
    name: ${hedera.mirror.db.name}
    password: ${hedera.mirror.db.password}
    url: jdbc:postgresql://${hedera.mirror.db.host}:${hedera.mirror.db.port}/${hedera.mirror.db.name}
    username: ${hedera.mirror.db.username}
  flyway:
    connectRetries: 20
    baselineOnMigrate: true
    baselineVersion: 0
    ignoreMissingMigrations: true
    placeholders:
      api-password: ${hedera.mirror.db.api-password}
      api-user: ${hedera.mirror.db.api-username}
      db-name: ${hedera.mirror.db.name}
      db-user: ${hedera.mirror.db.username}
  jpa:
    properties:
      hibernate:
        generate_statistics: true
  task:
    scheduling:
      pool:
        size: 6
  test:
    database:
      replace: NONE
