debug: true
hedera:
  mirror:
    db:
      apiPassword: mirror_api_pass
      apiUsername: mirror_api
      host: 127.0.0.1
      name: mirror_node
      password: mirror_node_pass
      port: 5432
      username: mirror_node
logging:
  level:
    root: warn
    com.hedera.mirror.importer: info
    org.flywaydb.core.internal.command.DbMigrate: info
    org.springframework.boot: trace
    #org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      elastic:
        enabled: false
        index: mirror
        step: 30s
      prometheus:
        step: 30s
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: hedera-mirror-importer
  cloud:
    kubernetes:
      reload:
        enabled: true
      secrets:
        paths: /usr/etc/${spring.application.name}
  datasource:
    name: ${hedera.mirror.db.name}
    password: ${hedera.mirror.db.password}
    url: jdbc:postgresql://${hedera.mirror.db.host}:${hedera.mirror.db.port}/${hedera.mirror.db.name}?&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${hedera.mirror.db.username}
  flyway:
    connectRetries: 10
    baselineOnMigrate: true
    baselineVersion: 0
    ignoreMissingMigrations: true
    placeholders:
      api-password: ${hedera.mirror.db.api-password}
      api-user: ${hedera.mirror.db.api-username}
      db-name: ${hedera.mirror.db.name}
      db-user: ${hedera.mirror.db.username}
  jpa:
    properties:
      hibernate:
        generate_statistics: true
  task:
    scheduling:
      pool:
        size: 6
  test:
    database:
      replace: NONE
