hedera:
  mirror:
    importer:
      db:
        host: 127.0.0.1
        loadBalance: false
        name: mirror_node
        owner: ${hedera.mirror.importer.db.username}
        ownerPassword: ${hedera.mirror.importer.db.password}
        password: mirror_node_pass
        port: 26257
        restPassword: mirror_api_pass
        restUsername: mirror_api
        schema: public
        username: mirror_node
logging:
  level:
    root: warn
    com.hedera.mirror.importer: info
    org.flywaydb.core.internal.command.DbMigrate: info
    #org.hibernate.type.descriptor.sql.BasicBinder: trace
management:
  endpoints:
    web:
      exposure:
        include: health, info, loggers, prometheus
  health:
    pubsub:
      # Just importing pubsub deps enables its health checker and it requires auth credentials.
      # Setting spring.cloud.gcp.pubsub.enabled=false is not enough to disable the pubsub health check.
      enabled: ${spring.cloud.gcp.pubsub.enabled}
  metrics:
    export:
      elastic:
        autoCreateIndex: false
        enabled: false
        index: mirror
        indexDateFormat: yyyy-MM-dd
        step: 30s
      prometheus:
        step: 30s
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      group:
        liveness:
          include: ping, streamFileActivity
        readiness:
          include: db, diskSpace, ping, redis, streamFileActivity
server:
  shutdown: graceful
spring:
  application:
    name: hedera-mirror-importer
  cloud:
    gcp:
      core:
        enabled: false
      pubsub:
        enabled: false
    kubernetes:
      reload:
        enabled: true
      secrets:
        paths: /usr/etc/${spring.application.name}
  datasource:
    name: ${hedera.mirror.importer.db.name}
    password: ${hedera.mirror.importer.db.password}
    url: jdbc:postgresql://${hedera.mirror.importer.db.host}:${hedera.mirror.importer.db.port}/${hedera.mirror.importer.db.name}?sslmode=require
    username: ${hedera.mirror.importer.db.username}
    hikari:
      data-source-properties:
        #loggerLevel: TRACE
        logUnclosedConnections: true
        reWriteBatchedInserts: true
      maximumPoolSize: 14 # recommended connections = ((core_count * 2) + effective_spindle_count), though somewhat outdated as we use SSDs
  flyway:
    baselineOnMigrate: true
    connectRetries: 20
    ignoreMissingMigrations: true
    placeholders:
      api-password: ${hedera.mirror.importer.db.restPassword}
      api-user: ${hedera.mirror.importer.db.restUsername}
      autovacuumFreezeMaxAgeInsertOnly: 100000
      autovacuumVacuumInsertThresholdCryptoTransfer: 300000
      autovacuumVacuumInsertThresholdTokenTransfer: 2000
      autovacuumVacuumInsertThresholdTransaction: 100000
      chunkIdInterval: 100000
      chunkTimeInterval: 86400000000000
      compressionAge: 604800000000000
      db-name: ${hedera.mirror.importer.db.name}
      db-user: ${hedera.mirror.importer.db.username}
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        globally_quoted_identifiers: true
        jdbc:
          batch_size: 250
        order_inserts: true
        order_updates: true
    show-sql: false
  lifecycle:
    timeout-per-shutdown-phase: 20s
  task:
    scheduling:
      pool:
        size: 6
  test:
    database:
      replace: NONE
