hedera:
  mirror:
    importer:
      db:
        host: 127.0.0.1
        name: mirror_node
        password: mirror_node_pass
        port: 5432
        restPassword: mirror_api_pass
        restUsername: mirror_api
        username: mirror_node
logging:
  level:
    root: warn
    com.hedera.mirror.importer: info
    org.flywaydb.core.internal.command.DbMigrate: info
    #org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  health:
    pubsub:
      # Just importing pubsub deps enables its health checker and it requires auth credentials.
      # Setting spring.cloud.gcp.pubsub.enabled=false is not enough to disable the pubsub health check.
      enabled: ${spring.cloud.gcp.pubsub.enabled}
  metrics:
    export:
      elastic:
        autoCreateIndex: false
        enabled: false
        index: mirror
        step: 30s
      prometheus:
        step: 30s
    tags:
      application: ${spring.application.name}
spring:
  application:
    name: hedera-mirror-importer
  cloud:
    gcp:
      pubsub:
        enabled: false
    kubernetes:
      reload:
        enabled: true
      secrets:
        paths: /usr/etc/${spring.application.name}
  datasource:
    name: ${hedera.mirror.importer.db.name}
    password: ${hedera.mirror.importer.db.password}
    url: jdbc:postgresql://${hedera.mirror.importer.db.host}:${hedera.mirror.importer.db.port}/${hedera.mirror.importer.db.name}
    username: ${hedera.mirror.importer.db.username}
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
  flyway:
    connectRetries: 20
    baselineOnMigrate: true
    baselineVersion: 0
    ignoreMissingMigrations: true
    placeholders:
      api-password: ${hedera.mirror.importer.db.restPassword}
      api-user: ${hedera.mirror.importer.db.restUsername}
      db-name: ${hedera.mirror.importer.db.name}
      db-user: ${hedera.mirror.importer.db.username}
  jpa:
    properties:
      hibernate:
        generate_statistics: true
  task:
    scheduling:
      pool:
        size: 6
  test:
    database:
      replace: NONE
