name: "Code scan"

on:
  push:
    branches: [ master, release/**, rosetta ]
  pull_request:
    branches: [ master, release/**, rosetta ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: --batch-mode --no-transfer-progress --show-version -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go', 'java', 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2

      # If this run was triggered by a pull request event, then checkout
      # the head of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
        if: ${{ matrix.language != 'java'  }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        if: ${{ matrix.language == 'java'  }}
        with:
          java-version: 11

      - name: Maven build
        run: ./mvnw ${MAVEN_CLI_OPTS} clean package -DskipTests
        if: ${{ matrix.language == 'java'  }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
